#!/bin/bash
echo 'running post-recieve . . .'
while read oldrev newrev ref
do
    # only if master
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=/home/webapps/coasters/ --git-dir=/home/webapps/git/coasters-node.git/ checkout -f
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master branch may be deployed on this server."
    fi

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD^ HEAD)"
echo $changed_files

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run node/package.json "cd /home/webapps/coasters/node && npm install"

/home/webapps/.npm-global/bin/forever stop /home/webapps/coasters/node/index.js
/home/webapps/.npm-global/bin/forever start /home/webapps/coasters/node/index.js
done